export const FETCH_TASKS_BEGIN = 'FETCH_TASKS_BEGIN';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';
export const SEARCH_UPDATE_TASK = 'SEARCH_UPDATE_TASK';
export const FILTER_UPDATE_TASK = 'FILTER_UPDATE_TASK';
